apiVersion: v1
kind: Service
metadata:
  name: kube-watchman
  labels:
    app: kube-watchman
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kube-watchman
    component: controller
