name: Build and Test

on:
  [workflow_dispatch, push]
jobs:
  buid-and-test:
    name: Build and Testing deployment to k3d cluster
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: AbsaOSS/k3d-action@v2
        name: "Create single k3d Cluster with imported Registry"
        with:
          cluster-name: cluster-1
          args: >-
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
      - name: Cluster info
        run: |
          kubectl cluster-info --context k3d-cluster-1
      - name: Nodes
        run: |
          docker ps -a
          kubectl config use-context k3d-cluster-1
          kubectl get nodes -o wide
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53 
      - name: Test Go code
        run: |
          go mod tidy
          go test ./...          
      - name: "Docker Build"
        run: |
          docker build . -t supporttools/kubewatchman:CICD
          k3d image import supporttools/kubewatchman:CICD -c cluster-1 --verbose
      - name: Network
        run: docker network inspect k3d-cluster-1