name: Build

on:
  [workflow_dispatch, push]
jobs:
  buid-and-test:
    name: Build and Testing deployment to k3d cluster
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: AbsaOSS/k3d-action@v2
        name: "v1.27.3 - k3d cluster create"
        with:
          cluster-name: cluster-1-27-3
          args: >-
            --agents 3
            --no-lb
            --image docker.io/rancher/k3s:v1.27.3-k3s1
      - uses: AbsaOSS/k3d-action@v2
        name: "v1.26.6 - k3d cluster create"
        with:
          cluster-name: cluster-1-26-6
          args: >-
            --agents 3
            --no-lb
            --image docker.io/rancher/k3s:v1.26.6-k3s1
      - uses: AbsaOSS/k3d-action@v2
        name: "v1.25.11 - k3d cluster create"
        with:
          cluster-name: cluster-1-25-11
          args: >-
            --agents 3
            --no-lb
            --image docker.io/rancher/k3s:v1.25.11-k3s1
      - name: "Cluster info"
        run: |
          kubectl cluster-info --context k3d-cluster-1-27-3
          kubectl cluster-info --context k3d-cluster-1-26-6
          kubectl cluster-info --context k3d-cluster-1-25-11
      - name: "Nodes"
        run: |
          docker ps -a
          kubectl config use-context k3d-cluster-1-27-3
          kubectl get nodes -o wide
          kubectl config use-context k3d-cluster-1-26-6
          kubectl get nodes -o wide
          kubectl config use-context k3d-cluster-1-25-11
          kubectl get nodes -o wide  
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: false
      - name: Test Go code
        run: |
          go test ./...          
      - name: "Docker Build with Dynamic Tag"
        run: |
          TAG="CICD-${GITHUB_SHA}"
          echo "DOCKER_TAG=${TAG}" >> $GITHUB_ENV
          docker build . -t supporttools/kubewatchman:${TAG}
      - name: Import Image to k3d clusters
        run: |
          k3d image import supporttools/kubewatchman:${{ env.DOCKER_TAG }} -c cluster-1-27-3 --verbose
          k3d image import supporttools/kubewatchman:${{ env.DOCKER_TAG }} -c cluster-1-26-6 --verbose
          k3d image import supporttools/kubewatchman:${{ env.DOCKER_TAG }} -c cluster-1-25-11 --verbose
      - name: Network
        run: |
          docker network inspect k3d-cluster-1-27-3
          docker network inspect k3d-cluster-1-26-6
          docker network inspect k3d-cluster-1-25-11