name: Single cluster on default network

on:
  [workflow_dispatch, push]
jobs:
  k3d-single-cluster-demo:
    name: Single cluster on default network
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: AbsaOSS/k3d-action@v2
        name: "Create single k3d Cluster with imported Registry"
        with:
          cluster-name: test-cluster-1
          k3d-version: v5.5.1
          args: >-
            --agents 3
            --no-lb
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
      - name: Cluster info
        run: |
          kubectl cluster-info --context k3d-test-cluster-1
      - name: Nodes
        run: |
          docker ps -a
          kubectl config use-context k3d-test-cluster-1
          kubectl get nodes -o wide
      - name: "Docker Build"
        run: |
          docker build . -t supporttools/kubewatchman:CICD
          k3d image import supporttools/kubewatchman:CICD -c test-cluster-1 --verbose
      - name: Network
        run: docker network inspect k3d-test-cluster-1